controller_list:
  - name: arm
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: gripper
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      []
